"""Ceating_DB

Revision ID: ae0f9de8b567
Revises: 
Create Date: 2025-01-14 14:41:31.964293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0f9de8b567'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.alter_column('subscription_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_customer', schema=None) as batch_op:
        batch_op.alter_column('subscription_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
